// Projects — verified 27 Sep 2026 against gh repos + READMEs.
// kind: solo (personal) | team (owned lane, read lanes not solo credit)
//      | practice (name + real one-liner + link, no deep dive).
export interface Project {
  slug: string;
  name: string;
  bucket: "projects" | "collaborations" | "practice";
  repo: string;
  upstream?: string;
  kind: "solo" | "team" | "practice";
  period: string;
  status: string;
  blurb: string;
  stack: string[];
  links: { github: string; arxiv?: string; doi?: string };
  lane?: string[];
  evidence: string[];
  motivation?: string;
}

export const projects: Project[] = [
  {
    slug: "ice",
    name: "ICE — Infinite Context Engine",
    bucket: "projects",
    repo: "Deepnar/ice",
    kind: "solo",
    period: "Jun 2026 — Present",
    status: "research · v3 system line active (paper line: frozen v2)",
    blurb:
      "A local-first memory layer for conversational AI: persistent, structured memory for any OpenAI-compatible model, running entirely on your own hardware.",
    stack: ["Python", "PyTorch", "FastAPI", "PostgreSQL + pgvector", "SQLAlchemy", "Docker", "Ollama"],
    links: { github: "https://github.com/Deepnar/ice", arxiv: "https://arxiv.org/abs/2609.16730", doi: "https://doi.org/10.5281/zenodo.21759702" },
    evidence: [
      "Structured episodic, document, procedural and temporal-graph stores behind an OpenAI-compatible proxy.",
      "Pre-flight classifier: multi-head PyTorch head over frozen Qwen3-Embedding-0.6B — 27 labels across topic, intent and context-reliance; calibrated routing decides when retrieval fires at all.",
      "Hybrid retrieval (lexical · vector · graph · procedural · document · timeline) with rank fusion, dedup and bounded token budgets.",
      "LSREP: a longitudinal state-replay protocol for evaluating conversational memory as it evolves over time.",
      "Frozen v2 paper-run: 1,985 turns · 1,211 probes · 50 checkpoints (LSREP replay with evolving ground truth). Tied vector-RAG on answer quality (paired Δ +0.00, 95% CI [−0.07, +0.07]) while injecting 32% fewer fragments; won 30.6% vs 21.2% of blind comparisons.",
      "Density stress: the unbudgeted baseline failed 94.2% of 154 probes; ICE scored a mean 4.33. Ablation isolated rank fusion as corrective (−0.74 without, +0.82 recovered).",
      "Tagged v2-paper-eval on GitHub (★3); paper, source, harness and audit public under Apache-2.0; v3 system-repair line in progress.",
      "LSREP belongs to the v2 line: it replays long conversations turn by turn, rebuilds memory at successive checkpoints, and scores against facts that get superseded mid-run."
    ],
    motivation:
      "Every chat session starts from zero and larger context windows didn't fix it — a window is a buffer, not a memory. The central finding: retrieval quality is governed by what you leave out, not by retrieving more.",
  },
  {
    slug: "presentation-forge",
    name: "Presentation Forge",
    bucket: "projects",
    repo: "Deepnar/presentation-forge",
    kind: "solo",
    period: "Aug — Sep 2026",
    status: "active · self-hosted",
    blurb:
      "Academic deck generator: topic in, researched themed .pptx out. A gateway Auto tier (mimo-vision drafts, flash facts) judges output quality; local Ollama supported, BYOK otherwise; Docker-first, self-hostable.",
    stack: ["Node.js", "React/Vite", "Ollama", "SQLite", "Docker"],
    links: { github: "https://github.com/Deepnar/presentation-forge" },
    evidence: [
      "Tagged v0.1.0 on GitHub (★15); 95 test files, ~790 test cases.",
      "74 slide types · 34 themes with deterministic rendering and schema validation.",
      "Human-approval gates, critique pass and reproducible reports with automated checks.",
      "Local-model support (Ollama) or BYOK providers; no inference bill required.",
    ],
    motivation:
      "Built to make researched decks reproducible artifacts instead of one-off slides — sources in, editable files out, every step checkable.",
  },
  {
    slug: "timetable-generator",
    name: "Timetable Generator",
    bucket: "projects",
    repo: "Deepnar/timetable-generator",
    kind: "solo",
    period: "Mar 2026 — Present",
    status: "active development",
    blurb:
      "Constraint-driven scheduling service for colleges: rooms, faculty, groups and subjects in; ranked, publishable timetables out.",
    stack: ["FastAPI", "PostgreSQL", "SQLAlchemy", "Alembic", "Google OR-Tools", "Docker"],
    links: { github: "https://github.com/Deepnar/timetable-generator" },
    evidence: [
      "Greedy + OR-Tools CP-SAT solvers under explicit hard constraints and weighted soft-constraint scoring.",
      "Authenticated REST APIs with audit/publishing workflows, shared-resource reservations and cross-timetable safety.",
      "Exports timetables to PDF/CSV/iCal; ranked candidates with weighted soft-constraint scoring.",
      "Data-driven constraint registry; no post-generation cleanup hacks.",
    ],
    motivation:
      "Scheduling breaks when constraints live in people's heads. This puts them in a registry and lets the solver argue with reality instead.",
  },
  {
    slug: "prompt-routing-classifier",
    name: "Prompt Routing Classifier",
    bucket: "projects",
    repo: "Deepnar/prompt-routing-classifier",
    kind: "solo",
    period: "Mar 2026",
    status: "complete · basis for ICE router",
    blurb:
      "Multi-label topic + intent classifier for routing prompts to specialised models: sentence embeddings + one-vs-rest logistic regression, CPU-only.",
    stack: ["Python", "sentence-transformers", "scikit-learn", "NumPy", "Pandas"],
    links: { github: "https://github.com/Deepnar/prompt-routing-classifier" },
    evidence: [
      "5,100-prompt labelled corpus with documented dataset, training path and evaluation split.",
      "Held-out F1 0.68 (topic) / 0.56 (intent); CPU-only inference.",
      "Routing design reused as the basis for ICE's pre-flight classifier.",
    ],
    motivation:
      "Built to answer a concrete question: can a tiny CPU classifier route prompts well enough that a big model never has to guess about context?",
  },
  {
    slug: "nexus",
    name: "NEXUS Fraud Detection",
    bucket: "collaborations",
    repo: "Deepnar/NEXUS-Fraud-Detection",
    upstream: "Rishit1769/NEXUS-Fraud-Detection",
    kind: "team",
    period: "Sep 2026",
    status: "team · expansion PR merged upstream",
    blurb:
      "Fraud-detection platform (transactions + messages + URLs). I took the deterministic-rules foundation and added a full transaction fraud head, a stronger message head, a debiased URL head, website flows and an admin-swappable AI provider — while removing the WhatsApp/n8n dependency.",
    stack: ["TypeScript", "Next.js", "Python", "XGBoost", "scikit-learn", "MySQL", "Prisma"],
    links: { github: "https://github.com/Rishit1769/NEXUS-Fraud-Detection/pull/1" },
    lane: [
      "transaction fraud head (XGBoost + calibration)",
      "message-head upgrade (TF-IDF + direction features)",
      "URL-head debias",
      "website txn flows + admin AI-provider console",
      "removed WhatsApp/n8n dependency",
    ],
    evidence: [
      "PR +3,455/−1,228 across 59 files, merged upstream; trains and serves from the repo alone.",
      "Transaction head (XGBoost + Optuna + isotonic calibration, grouped User-Card split): test PR-AUC 0.707; fresh-seed check 0.689 — reported in the PR with eval ledger.",
      "Message head (char+word TF-IDF + direction features + augmentation): 11/18 → 18/18 on unseen probes; URL head debiased (bare-domain + www-bias fixes + ~30k synthetic benign-with-path rows): 12/20 → 19/20.",
      "Casual + batch website flows, officer queue/txn workspace, admin console to swap AI provider without redeploying.",
      "Left honest loose ends in the PR itself: per-head operating thresholds, README rewrite, SMTP/auth gaps — flagged, not hidden.",
    ],
  },
  {
    slug: "civicresolve",
    name: "CivicResolve",
    bucket: "collaborations",
    repo: "Deepnar/CivicResolve",
    upstream: "Newer1107/CivicResolve",
    kind: "team",
    period: "Aug 2025 — Mar 2026",
    status: "team of 6 · SIH ×2 rounds, DIPEX state final",
    blurb:
      "Civic-reporting platform: SIH 2025 (cleared two institute rounds) → DIPEX 2026 (MMR regional → Maharashtra-Goa state final).",
    stack: ["TypeScript", "MySQL", "Prisma", "Docker"],
    links: { github: "https://github.com/Deepnar/CivicResolve" },
    lane: [
      "AI Observation Engine (street-imagery verification, worker, tests, docs)",
      "security threat model + infrastructure cost model",
      "pitch at SIH ×2 rounds and DIPEX state final",
    ],
    evidence: [
      "Post-competition AI Observation Engine contribution (street-imagery verification, background worker, tests) merged after maintainer review.",
      "Positioned against CPGRAMS; team grew 2 → 6.",
    ],
  },
  {
    slug: "rapidrail",
    name: "RapidRail",
    bucket: "collaborations",
    repo: "Deepnar/rapidrail-utf-project",
    kind: "team",
    period: "2026",
    status: "3-person team · student demo",
    blurb:
      "Full-stack suburban rail ticketing with QR validation, digital wallet and fare engine. Java, Spring Boot, MySQL.",
    stack: ["Java", "Spring Boot 3", "MySQL", "JPA", "ZXing QR", "Razorpay (test mode)"],
    links: { github: "https://github.com/Deepnar/rapidrail-utf-project" },
    lane: [
      "core service: booking, wallet, QR e-tickets, fare engine",
      "README + docs, secured API keys into local profile",
    ],
    evidence: [
      "My commits: initial service, core booking/wallet/QR/fare-engine code, README + docs, secured API keys into a local properties profile.",
      "Payment status is honest by design: Razorpay test mode (rzp_test_), signature verification + wallet credit work, but no live keys, no webhook handler — a student demo, not production billing.",
    ],
  },
  {
    slug: "iis-mini",
    name: "IIS Mini Fraud Project",
    bucket: "collaborations",
    repo: "Deepnar/iis-mini-fraud",
    kind: "team",
    period: "Sep 2026",
    status: "team ML plan · Person-1 lane",
    blurb:
      "Credit-card fraud modeling split across three lanes.",
    stack: ["Python", "scikit-learn", "pandas", "uv"],
    links: { github: "https://github.com/Deepnar/iis-mini-fraud" },
    lane: [
      "Person-1 lane: classical baselines (LogReg + RF, full sweep)",
      "REPORT_PERSON1.md + outputs",
    ],
    evidence: [
      "Person-1 baseline scripts (inspect → baseline → full sweep) with outputs and REPORT_PERSON1.md, on IBM synthetic txn data (accuracy rejected as a metric).",
      "Locked test @0.24: RF precision 0.784 · recall 0.592 · F1 0.674 · PR-AUC 0.618 (29/49 fraud, 8 FP). LogReg best PR-AUC 0.206 — the linear boundary can't capture fraud interactions.",
      "Teammates ran the tuning (Person 2) and XGBoost/imbalance lanes (Person 3); team ML plan in-repo.",
    ],
  },
  {
    slug: "micrograd-from-scratch",
    name: "micrograd-from-scratch",
    bucket: "practice",
    repo: "Deepnar/micrograd-from-scratch",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "A minimal autodiff engine and neural network from first principles: scalar computation graph, manual backpropagation, no ML libraries.",
    stack: ["Jupyter Notebook", "Python"],
    links: { github: "https://github.com/Deepnar/micrograd-from-scratch" },
    evidence: [],
  },
  {
    slug: "gradient-descent-from-scratch",
    name: "gradient-descent-from-scratch",
    bucket: "practice",
    repo: "Deepnar/gradient-descent-from-scratch",
    kind: "practice",
    period: "Jan — Feb 2026",
    status: "practice",
    blurb: "Linear regression and gradient descent in pure NumPy — analytical gradients, MSE loss, convergence behaviour.",
    stack: ["NumPy", "Python"],
    links: { github: "https://github.com/Deepnar/gradient-descent-from-scratch" },
    evidence: [],
  },
  {
    slug: "wine-quality-regression",
    name: "wine-quality-regression",
    bucket: "practice",
    repo: "Deepnar/wine-quality-regression",
    kind: "practice",
    period: "Jan — Feb 2026",
    status: "practice",
    blurb: "Regression on physicochemical features — random forest and gradient boosting compared on MAE, MSE and R².",
    stack: ["scikit-learn", "Pandas"],
    links: { github: "https://github.com/Deepnar/wine-quality-regression" },
    evidence: [],
  },
  {
    slug: "titanic-ml-pipeline",
    name: "titanic-ml-pipeline",
    bucket: "practice",
    repo: "Deepnar/titanic-ml-pipeline",
    kind: "practice",
    period: "Jan — Feb 2026",
    status: "practice",
    blurb: "End-to-end classification pipeline: cleaning, feature engineering, and a comparison of logistic regression, random forest and naive Bayes.",
    stack: ["scikit-learn", "Pandas"],
    links: { github: "https://github.com/Deepnar/titanic-ml-pipeline" },
    evidence: [],
  },
  {
    slug: "ds-practice",
    name: "DS-Practice",
    bucket: "practice",
    repo: "Deepnar/DS-Practice",
    kind: "practice",
    period: "—",
    status: "practice · coursework",
    blurb: "Algorithms, data structures, OS and networking programs from Computer Engineering coursework — implemented from the algorithm, not adapted from a library.",
    stack: ["Python", "Java"],
    links: { github: "https://github.com/Deepnar/DS-Practice" },
    evidence: [],
  },
  {
    slug: "movie-ticket-booking",
    name: "movie-ticket-booking",
    bucket: "practice",
    repo: "Deepnar/movie-ticket-booking",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Spring Boot REST-CRUD app for booking movie tickets: browse movies, book seats, pay from a built-in wallet, QR-coded e-ticket; admin manages movies, cinemas, shows.",
    stack: ["Java", "Spring Boot", "MySQL"],
    links: { github: "https://github.com/Deepnar/movie-ticket-booking" },
    evidence: [],
  },
  {
    slug: "hostel-room-allocation-system",
    name: "hostel-room-allocation-system",
    bucket: "practice",
    repo: "Deepnar/hostel-room-allocation-system",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Core-Java web app for hostel room allocation: role-based access (student, guest, admin) and conflict-free booking logic in an MVC layout.",
    stack: ["Java", "Servlets", "JDBC", "MySQL"],
    links: { github: "https://github.com/Deepnar/hostel-room-allocation-system" },
    evidence: [],
  },
  {
    slug: "ppo-clip-demo",
    name: "ppo-clip-demo",
    bucket: "practice",
    repo: "Deepnar/ppo-clip-demo",
    kind: "practice",
    period: "—",
    status: "practice · classroom demo",
    blurb: "Small classroom demo of PPO-Clip on Gymnasium's Pendulum-v1: trains and evaluates PPO, ships a trained model, runs it visually.",
    stack: ["Python"],
    links: { github: "https://github.com/Deepnar/ppo-clip-demo" },
    evidence: [],
  },
  {
    slug: "quiz-game",
    name: "Quiz-Game",
    bucket: "practice",
    repo: "Deepnar/Quiz-Game",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Command-line quiz game in Python with MySQL: multiple participants, difficulty levels, admin question management, score tracking.",
    stack: ["Python", "MySQL"],
    links: { github: "https://github.com/Deepnar/Quiz-Game" },
    evidence: [],
  },
  {
    slug: "python-practice-lab",
    name: "python-practice-lab",
    bucket: "practice",
    repo: "Deepnar/python-practice-lab",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Learning repository across Python domains: data science, image processing, web, data structures and algorithms.",
    stack: ["Python", "Jupyter Notebook"],
    links: { github: "https://github.com/Deepnar/python-practice-lab" },
    evidence: [],
  },
  {
    slug: "rust-lab",
    name: "rust-lab",
    bucket: "practice",
    repo: "Deepnar/rust-lab",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Rust practice repository.",
    stack: ["Rust"],
    links: { github: "https://github.com/Deepnar/rust-lab" },
    evidence: [],
  },
  {
    slug: "ecommerce-client",
    name: "EcommerceClient",
    bucket: "practice",
    repo: "Deepnar/EcommerceClient",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Static multi-page storefront in plain HTML/CSS/JS: categories, cart, account pages — no framework, no backend.",
    stack: ["HTML", "CSS", "JavaScript"],
    links: { github: "https://github.com/Deepnar/EcommerceClient" },
    evidence: [],
  },
  {
    slug: "cricbuzz-app",
    name: "CricbuzzApp",
    bucket: "practice",
    repo: "Deepnar/CricbuzzApp",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Cricket match simulation: Java backend plus a standalone interactive frontend for matches, teams and players.",
    stack: ["Java", "HTML", "CSS", "JavaScript"],
    links: { github: "https://github.com/Deepnar/CricbuzzApp" },
    evidence: [],
  },
  {
    slug: "python-backend",
    name: "python-backend",
    bucket: "practice",
    repo: "Deepnar/python-backend",
    kind: "practice",
    period: "—",
    status: "practice",
    blurb: "Python backend practice repository.",
    stack: ["Python"],
    links: { github: "https://github.com/Deepnar/python-backend" },
    evidence: [],
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
